version: "3.9"

services:
  db:
    image: postgres:15
    container_name: chatbot-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-banking_chatbot}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: banking-chatbot-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/banking_chatbot}
      ENVIRONMENT: ${ENVIRONMENT:-production}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS:-2}
      AUTO_MIGRATE: ${AUTO_MIGRATE:-true}
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/health"]
      interval: 20s
      timeout: 5s
      retries: 5

volumes:
  db-data:
