"""Update audit_logs with created_at and updated_at

Revision ID: 06b06c50a4bf
Revises: 6b03629f3aed
Create Date: 2025-10-04 18:03:42.496684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b06c50a4bf'
down_revision: Union[str, Sequence[str], None] = '6b03629f3aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server_default to handle existing rows
    op.add_column('audit_logs', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    op.add_column('audit_logs', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'updated_at')
    op.drop_column('audit_logs', 'created_at')
    # ### end Alembic commands ###
